version: '3'

services:
  factorio:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
    #  - ./src:/src
     # - ./include:/include
      - ./docker:/src
