on:
  pull_request:
    branches:
      - main  

jobs:
  style-check:
    name: Check Code Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ClangFormat
        run: |
          sudo apt update
          sudo apt install -y clang-format

      - name: Check Code Style
        run: clang-format --version
